// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANi52ofxacGtVLjtMP7vPZaxijMyHxWG4',
    appId: '1:1010522056377:web:6228feb70f723bcbf45d68',
    messagingSenderId: '1010522056377',
    projectId: 'prakriti-ayurtech-iitj',
    authDomain: 'prakriti-ayurtech-iitj.firebaseapp.com',
    storageBucket: 'prakriti-ayurtech-iitj.appspot.com',
    measurementId: 'G-SQXPG11NER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvU49_mFT2E8SAfg_oGYtsopVNd7ylpBw',
    appId: '1:1010522056377:android:89971397e5926087f45d68',
    messagingSenderId: '1010522056377',
    projectId: 'prakriti-ayurtech-iitj',
    storageBucket: 'prakriti-ayurtech-iitj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhfgJauwopadKvYgM4EyZDih3MUGMKH7c',
    appId: '1:1010522056377:ios:d97a2193bdae28aef45d68',
    messagingSenderId: '1010522056377',
    projectId: 'prakriti-ayurtech-iitj',
    storageBucket: 'prakriti-ayurtech-iitj.appspot.com',
    iosClientId: '1010522056377-g7uf0jhndd6v2dpnc7k3dcsaqcf8t98b.apps.googleusercontent.com',
    iosBundleId: 'com.example.prakriti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhfgJauwopadKvYgM4EyZDih3MUGMKH7c',
    appId: '1:1010522056377:ios:bf6ad43642450d0af45d68',
    messagingSenderId: '1010522056377',
    projectId: 'prakriti-ayurtech-iitj',
    storageBucket: 'prakriti-ayurtech-iitj.appspot.com',
    iosClientId: '1010522056377-ul115l7tqi6efj3lb7uapg06t28lr7ih.apps.googleusercontent.com',
    iosBundleId: 'com.example.prakriti.RunnerTests',
  );
}
